version: '2'
services:
    web:
        build: .
        command: yarn run dev
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        depends_on: 
            - mongo
        environment: 
            MONGO_URL: mongodb://localhost:27017/r2
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
